import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["tests/unit/**/*.test.ts"],
    coverage: {
      provider: "v8",
      include: ["lib/**/*.ts"],
      exclude: [
        "lib/store/**",
        "lib/db.ts",
        "lib/supabase.ts",
        "lib/auth.ts",
        "lib/api-keys.ts",
        "lib/ensure-user.ts",
        "lib/limits.ts",
        "lib/webhooks.ts",
        "lib/logger.ts",
        "lib/credits/**",
        "lib/usage/**",
        "lib/projects/**",
        "lib/deploy/buildProject.ts",
        "lib/deploy/deployManager.ts",
        "lib/deploy/deployRegistry.ts",
        "lib/deploy/vercelClient.ts",
        "lib/preview/previewEngine.ts",
        "lib/preview/previewHotReload.ts",
        "lib/preview/previewManager.ts",
        "lib/preview/processRegistry.ts",
        "lib/preview/processSupervisor.ts",
        "lib/preview/quotaManager.ts",
        "lib/preview/sandbox.ts",
        "lib/preview/startPreview.ts",
        "lib/preview/stopPreview.ts",
        "lib/preview/streamLogs.ts",
        "lib/preview/watcher.ts",
        "lib/preview/lifecycle.ts",
        "lib/preview/frameworkDetector.ts",
        "lib/build/buildPipeline.ts",
        "lib/build/artifactManager.ts",
        "lib/build/capacitorBuilder.ts",
        "lib/build/electronBuilder.ts",
        "lib/build/pwaBuilder.ts",
        "lib/build/tauriBuilder.ts",
        "lib/build/platformDetector.ts",
        "lib/build/buildJobQueue.ts",
        "lib/ai/commitMessageGenerator.ts",
        "lib/ai/errorDetector.ts",
        "lib/ai/provider.ts",
        "lib/ai/orchestrator.ts",
        "lib/ai/projectArchitect.ts",
        "lib/ai/projectAnalyzer.ts",
        "lib/ai/dependencyAnalyzer.ts",
        "lib/ai/refactorEngine.ts",
        "lib/ai/autoRefactor.ts",
        "lib/ai/autoFixer.ts",
        "lib/ai/aiExecutor.ts",
        "lib/ai/aiSuggestions.ts",
        "lib/ai/architectures.ts",
        "lib/ai/aiActions.ts",
        "lib/ai/aiMultiPreviewParser.ts",
        "lib/ai/aiPreviewParser.ts",
        "lib/ai/aiTypes.ts",
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "."),
    },
  },
});
