"use client";

import { useWorkspaceStore } from "@/store/useWorkspaceStore";
import { useAIMultiPreviewStore } from "@/store/useAIMultiPreviewStore";

export function generateCommitMessage() {
  const previews = useAIMultiPreviewStore.getState().previews;
  const workspace = useWorkspaceStore.getState();

  if (previews.length === 0) {
    return "No changes detected — nothing to commit.";
  }

  const lines: string[] = [];

  lines.push("feat: update project files");
  lines.push("");
  lines.push("Changes:");
  lines.push("");

  previews.forEach((p) => {
    const oldContent = workspace.files[p.file]?.content ?? "";
    const newContent = p.newContent ?? "";

    const oldLines = oldContent.split("\n").length;
    const newLines = newContent.split("\n").length;

    const diff = newLines - oldLines;

    lines.push(
      `- ${p.file} (${diff > 0 ? "+" + diff : diff} lines changed)`
    );
  });

  lines.push("");
  lines.push("Generated by Prestige Build AI.");

  return lines.join("\n");
}
